### ISSUE TITLE
Post-HENRI  inset plot cleanup

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/ADCIRCSupportTools#5]
Make shorter in the y-dir, so that they do not take up as much screen real estate. 
Remove “versus MSL” from all labeling
Spell out WL
Remove “station name =”
Remove time range subtitle
Legend labels: {Prediction, Nowcast, Observations, Difference}
Consider adding NOAA tidal prediction

**Comment by BrianOBlanton** [comment]
Jeff, once these changes show up in APSViz2 (i.e., "verified) please "close" this issue.

**Comment by jtilson** [comment]
All entries have been addressed and pushed to apsviz2. New apsviz2 advisories are successfully using this.
